#!/bin/sh

# Convenience script for running various idempotent source code cleanup scripts

set -e
set -x

scripts/docs-headings.py
scripts/generate-ini.py
scripts/whitespacecleanup.sh

hg files 'set:!binary()&grep("^#!.*python")' 'set:**.py' | xargs scripts/pyflakes
echo "no blocking problems found by $0"
